monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: critical
            handler:      grouped
        grouped:
            type:    group
            members: [streamed]
        streamed:
            type:  stream
            path:  '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        deduplicated:
            type:    deduplication
            handler: mailed
        mailed:
            type:         native_mailer
            from_email:   '%app.from_email%'
            to_email:     '%app.admin_email%'
            subject:      'An error occurred! %%message%%'
            level:        critical
            headers: ['Content-Type: text/html; charset=UTF-8']
